<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
Use Carbon\Carbon;

class DatabaseSeeder extends Seeder {

    /**
     * Seed the application's database.
     *
     * @return void
     */

    public function run() {

        DB::table('users')->insert([  //admin è il concessionario in realtà
            [ 'name' => 'Concessionario', 'cognome' => 'Concessionario',  'username' => 'concconc', 'password' => Hash::make('concconc'), 'livello' => 'concessionario','auto' => 'concconc','targa' => 'concconc','datavendita' =>  Carbon::create('2000','02','01') ,'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],

        ]);


        //le foto delle auto  si trovano in public/img/alloggi    perchè ho riutilizzato progetto precedente
        DB::table('auto')->insert([
            ['marca' => 'Fiat' , 'modello' => '500' , 'foto' => 'fiat500.png' , 'descrizione' => 'Stai cercando un modo ecologico e conveniente di spostarti in città? Allora questa auto elettrica potrebbe essere perfetta per te!Il nostro veicolo è alimentato da una o più potenti batterie al litio, che ti permetteranno di percorrere diverse centinaia di chilometri senza doverti preoccupare di fare il pieno. Inoltre, non emetterà alcun gas di scarico durante la guida, contribuendo a ridurre l'impatto ambientale.La guida di questa auto elettrica è fluida e silenziosa, rendendola ideale per il traffico cittadino. Non dovrai preoccuparti di fare il cambio dell'olio o di altre manutenzioni complesse, il che la rende anche conveniente da gestire a lungo termine.Se sei interessato a questa fantastica auto elettrica, non esitare a contattarci per maggiori informazioni o per fissare un appuntamento per una prova su strada. Siamo sicuri che una volta provata, non potrai più farne a meno!'],
            ['marca' => 'Audi' , 'modello' => 'A3' , 'foto' => 'audiA3.png' , 'descrizione' => 'Stai cercando un modo ecologico e conveniente di spostarti in città? Allora questa auto elettrica potrebbe essere perfetta per te!Il nostro veicolo è alimentato da una o più potenti batterie al litio, che ti permetteranno di percorrere diverse centinaia di chilometri senza doverti preoccupare di fare il pieno. Inoltre, non emetterà alcun gas di scarico durante la guida, contribuendo a ridurre l'impatto ambientale.La guida di questa auto elettrica è fluida e silenziosa, rendendola ideale per il traffico cittadino. Non dovrai preoccuparti di fare il cambio dell'olio o di altre manutenzioni complesse, il che la rende anche conveniente da gestire a lungo termine.Se sei interessato a questa fantastica auto elettrica, non esitare a contattarci per maggiori informazioni o per fissare un appuntamento per una prova su strada. Siamo sicuri che una volta provata, non potrai più farne a meno!'],
            ['marca' => 'Ferrari' , 'modello' => 'Purosangue' , 'foto' => 'FerrariPurosangue.png' , 'descrizione' => 'Stai cercando un modo ecologico e conveniente di spostarti in città? Allora questa auto elettrica potrebbe essere perfetta per te!Il nostro veicolo è alimentato da una o più potenti batterie al litio, che ti permetteranno di percorrere diverse centinaia di chilometri senza doverti preoccupare di fare il pieno. Inoltre, non emetterà alcun gas di scarico durante la guida, contribuendo a ridurre l'impatto ambientale.La guida di questa auto elettrica è fluida e silenziosa, rendendola ideale per il traffico cittadino. Non dovrai preoccuparti di fare il cambio dell'olio o di altre manutenzioni complesse, il che la rende anche conveniente da gestire a lungo termine.Se sei interessato a questa fantastica auto elettrica, non esitare a contattarci per maggiori informazioni o per fissare un appuntamento per una prova su strada. Siamo sicuri che una volta provata, non potrai più farne a meno!'],
            ['marca' => 'Hyundai' , 'modello' => 'i20' , 'foto' => 'Hyundaii20.png' , 'descrizione' => 'Stai cercando un modo ecologico e conveniente di spostarti in città? Allora questa auto elettrica potrebbe essere perfetta per te!Il nostro veicolo è alimentato da una o più potenti batterie al litio, che ti permetteranno di percorrere diverse centinaia di chilometri senza doverti preoccupare di fare il pieno. Inoltre, non emetterà alcun gas di scarico durante la guida, contribuendo a ridurre l'impatto ambientale.La guida di questa auto elettrica è fluida e silenziosa, rendendola ideale per il traffico cittadino. Non dovrai preoccuparti di fare il cambio dell'olio o di altre manutenzioni complesse, il che la rende anche conveniente da gestire a lungo termine.Se sei interessato a questa fantastica auto elettrica, non esitare a contattarci per maggiori informazioni o per fissare un appuntamento per una prova su strada. Siamo sicuri che una volta provata, non potrai più farne a meno!'],
            ['marca' => 'volkswagen' , 'modello' => 'golf' , 'foto' => 'golf.png' , 'descrizione' => 'Stai cercando un modo ecologico e conveniente di spostarti in città? Allora questa auto elettrica potrebbe essere perfetta per te!Il nostro veicolo è alimentato da una o più potenti batterie al litio, che ti permetteranno di percorrere diverse centinaia di chilometri senza doverti preoccupare di fare il pieno. Inoltre, non emetterà alcun gas di scarico durante la guida, contribuendo a ridurre l'impatto ambientale.La guida di questa auto elettrica è fluida e silenziosa, rendendola ideale per il traffico cittadino. Non dovrai preoccuparti di fare il cambio dell'olio o di altre manutenzioni complesse, il che la rende anche conveniente da gestire a lungo termine.Se sei interessato a questa fantastica auto elettrica, non esitare a contattarci per maggiori informazioni o per fissare un appuntamento per una prova su strada. Siamo sicuri che una volta provata, non potrai più farne a meno!'],
            ['marca' => 'Lamborghini' , 'modello' => 'Revuleto' , 'foto' => 'revuelto.png' , 'descrizione' => 'Stai cercando un modo ecologico e conveniente di spostarti in città? Allora questa auto elettrica potrebbe essere perfetta per te!Il nostro veicolo è alimentato da una o più potenti batterie al litio, che ti permetteranno di percorrere diverse centinaia di chilometri senza doverti preoccupare di fare il pieno. Inoltre, non emetterà alcun gas di scarico durante la guida, contribuendo a ridurre l'impatto ambientale.La guida di questa auto elettrica è fluida e silenziosa, rendendola ideale per il traffico cittadino. Non dovrai preoccuparti di fare il cambio dell'olio o di altre manutenzioni complesse, il che la rende anche conveniente da gestire a lungo termine.Se sei interessato a questa fantastica auto elettrica, non esitare a contattarci per maggiori informazioni o per fissare un appuntamento per una prova su strada. Siamo sicuri che una volta provata, non potrai più farne a meno!'],
            ['marca' => 'Fiat' , 'modello' => 'tipo' , 'foto' => 'tipo.png' , 'descrizione' => 'Stai cercando un modo ecologico e conveniente di spostarti in città? Allora questa auto elettrica potrebbe essere perfetta per te!Il nostro veicolo è alimentato da una o più potenti batterie al litio, che ti permetteranno di percorrere diverse centinaia di chilometri senza doverti preoccupare di fare il pieno. Inoltre, non emetterà alcun gas di scarico durante la guida, contribuendo a ridurre l'impatto ambientale.La guida di questa auto elettrica è fluida e silenziosa, rendendola ideale per il traffico cittadino. Non dovrai preoccuparti di fare il cambio dell'olio o di altre manutenzioni complesse, il che la rende anche conveniente da gestire a lungo termine.Se sei interessato a questa fantastica auto elettrica, non esitare a contattarci per maggiori informazioni o per fissare un appuntamento per una prova su strada. Siamo sicuri che una volta provata, non potrai più farne a meno!'],
            ['marca' => 'Alfa Romeo' , 'modello' => 'Giulia' , 'foto' => 'giulia.png' , 'descrizione' => 'Stai cercando un modo ecologico e conveniente di spostarti in città? Allora questa auto elettrica potrebbe essere perfetta per te!Il nostro veicolo è alimentato da una o più potenti batterie al litio, che ti permetteranno di percorrere diverse centinaia di chilometri senza doverti preoccupare di fare il pieno. Inoltre, non emetterà alcun gas di scarico durante la guida, contribuendo a ridurre l'impatto ambientale.La guida di questa auto elettrica è fluida e silenziosa, rendendola ideale per il traffico cittadino. Non dovrai preoccuparti di fare il cambio dell'olio o di altre manutenzioni complesse, il che la rende anche conveniente da gestire a lungo termine.Se sei interessato a questa fantastica auto elettrica, non esitare a contattarci per maggiori informazioni o per fissare un appuntamento per una prova su strada. Siamo sicuri che una volta provata, non potrai più farne a meno!'],
            ['marca' => 'Alfa Romeo' , 'modello' => 'Stelvio' , 'foto' => 'stelvio.png' , 'descrizione' => 'Stai cercando un modo ecologico e conveniente di spostarti in città? Allora questa auto elettrica potrebbe essere perfetta per te!Il nostro veicolo è alimentato da una o più potenti batterie al litio, che ti permetteranno di percorrere diverse centinaia di chilometri senza doverti preoccupare di fare il pieno. Inoltre, non emetterà alcun gas di scarico durante la guida, contribuendo a ridurre l'impatto ambientale.La guida di questa auto elettrica è fluida e silenziosa, rendendola ideale per il traffico cittadino. Non dovrai preoccuparti di fare il cambio dell'olio o di altre manutenzioni complesse, il che la rende anche conveniente da gestire a lungo termine.Se sei interessato a questa fantastica auto elettrica, non esitare a contattarci per maggiori informazioni o per fissare un appuntamento per una prova su strada. Siamo sicuri che una volta provata, non potrai più farne a meno!'],
            ['marca' => 'Renault' , 'modello' => 'Clio' , 'foto' => 'clio.png' , 'descrizione' => 'Stai cercando un modo ecologico e conveniente di spostarti in città? Allora questa auto elettrica potrebbe essere perfetta per te!Il nostro veicolo è alimentato da una o più potenti batterie al litio, che ti permetteranno di percorrere diverse centinaia di chilometri senza doverti preoccupare di fare il pieno. Inoltre, non emetterà alcun gas di scarico durante la guida, contribuendo a ridurre l'impatto ambientale.La guida di questa auto elettrica è fluida e silenziosa, rendendola ideale per il traffico cittadino. Non dovrai preoccuparti di fare il cambio dell'olio o di altre manutenzioni complesse, il che la rende anche conveniente da gestire a lungo termine.Se sei interessato a questa fantastica auto elettrica, non esitare a contattarci per maggiori informazioni o per fissare un appuntamento per una prova su strada. Siamo sicuri che una volta provata, non potrai più farne a meno!'],
            ['marca' => 'Ford' , 'modello' => 'Fiesta' , 'foto' => 'fiesta.png' , 'descrizione' => 'Stai cercando un modo ecologico e conveniente di spostarti in città? Allora questa auto elettrica potrebbe essere perfetta per te!Il nostro veicolo è alimentato da una o più potenti batterie al litio, che ti permetteranno di percorrere diverse centinaia di chilometri senza doverti preoccupare di fare il pieno. Inoltre, non emetterà alcun gas di scarico durante la guida, contribuendo a ridurre l'impatto ambientale.La guida di questa auto elettrica è fluida e silenziosa, rendendola ideale per il traffico cittadino. Non dovrai preoccuparti di fare il cambio dell'olio o di altre manutenzioni complesse, il che la rende anche conveniente da gestire a lungo termine.Se sei interessato a questa fantastica auto elettrica, non esitare a contattarci per maggiori informazioni o per fissare un appuntamento per una prova su strada. Siamo sicuri che una volta provata, non potrai più farne a meno!'],
            ]);


    }

}//chiude la classe seeder
